//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhiganshinaMilana420_MarryMe.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bouquet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bouquet()
        {
            this.CoupleFavorites = new HashSet<CoupleFavorites>();
            this.BouquetPhoto = new HashSet<BouquetPhoto>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> BouquetTypeId { get; set; }
        public Nullable<int> Price { get; set; }
        public string Description { get; set; }
    
        public virtual BouquetType BouquetType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoupleFavorites> CoupleFavorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BouquetPhoto> BouquetPhoto { get; set; }
    }
}
