//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhiganshinaMilana420_MarryMe.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoupleFavorites
    {
        public int Id { get; set; }
        public int CoupleId { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public Nullable<int> DecorationId { get; set; }
        public Nullable<int> ClothingGrommId { get; set; }
        public Nullable<int> DressBriedId { get; set; }
        public Nullable<int> AccessoryId { get; set; }
        public Nullable<int> HostId { get; set; }
        public Nullable<int> PhotographerVideographerId { get; set; }
        public Nullable<int> BouquetId { get; set; }
        public Nullable<int> StylistId { get; set; }
        public Nullable<int> MusicianId { get; set; }
        public Nullable<int> TransferId { get; set; }
        public Nullable<int> CakeId { get; set; }
        public string Description { get; set; }
    
        public virtual Accessory Accessory { get; set; }
        public virtual Bouquet Bouquet { get; set; }
        public virtual Cake Cake { get; set; }
        public virtual Clothing Clothing { get; set; }
        public virtual Couple Couple { get; set; }
        public virtual Host Host { get; set; }
        public virtual Musician Musician { get; set; }
        public virtual PhotographerVideographer PhotographerVideographer { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual Stylist Stylist { get; set; }
        public virtual Transfer Transfer { get; set; }
        public virtual Decoration Decoration { get; set; }
        public virtual Dress Dress { get; set; }
    }
}
