//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhiganshinaMilana420_MarryMe.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Couple
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Couple()
        {
            this.CoupleFavorites = new HashSet<CoupleFavorites>();
            this.HostBookingDates = new HashSet<HostBookingDates>();
            this.MusicianBookingDates = new HashSet<MusicianBookingDates>();
            this.PhotographerVideographerBookingDates = new HashSet<PhotographerVideographerBookingDates>();
            this.RestaurantBookingDates = new HashSet<RestaurantBookingDates>();
            this.StylistBookingDates = new HashSet<StylistBookingDates>();
            this.TransferBookingDates = new HashSet<TransferBookingDates>();
        }
    
        public int Id { get; set; }
        public int BrideId { get; set; }
        public int GroomId { get; set; }
        public Nullable<System.DateTime> WeddingDate { get; set; }
        public Nullable<int> WeddingStatusId { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string ContractPath { get; set; }
        public string MaterialsPath { get; set; }
        public Nullable<int> NumberGuests { get; set; }
        public Nullable<int> WeddingBudget { get; set; }
    
        public virtual Bride Bride { get; set; }
        public virtual Gromm Gromm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoupleFavorites> CoupleFavorites { get; set; }
        public virtual WeddingStatus WeddingStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HostBookingDates> HostBookingDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicianBookingDates> MusicianBookingDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotographerVideographerBookingDates> PhotographerVideographerBookingDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantBookingDates> RestaurantBookingDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StylistBookingDates> StylistBookingDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferBookingDates> TransferBookingDates { get; set; }
    }
}
