//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhiganshinaMilana420_MarryMe.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotographerVideographer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhotographerVideographer()
        {
            this.CoupleFavorites = new HashSet<CoupleFavorites>();
            this.PhotographerVideographerBookingDates = new HashSet<PhotographerVideographerBookingDates>();
            this.PhotographerVideographerPhoto = new HashSet<PhotographerVideographerPhoto>();
        }
    
        public int Id { get; set; }
        public string TeamName { get; set; }
        public Nullable<int> Price { get; set; }
        public string Description { get; set; }
        public Nullable<int> PhotographerTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoupleFavorites> CoupleFavorites { get; set; }
        public virtual PhotographerType PhotographerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotographerVideographerBookingDates> PhotographerVideographerBookingDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotographerVideographerPhoto> PhotographerVideographerPhoto { get; set; }
    }
}
