//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhiganshinaMilana420_MarryMe.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurant()
        {
            this.CoupleFavorites = new HashSet<CoupleFavorites>();
            this.RestaurantBookingDates = new HashSet<RestaurantBookingDates>();
            this.RestaurantPhoto = new HashSet<RestaurantPhoto>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> RestaurantTypeId { get; set; }
        public Nullable<int> Price { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string DocumentMenu { get; set; }
        public Nullable<int> Сapacity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoupleFavorites> CoupleFavorites { get; set; }
        public virtual RestaurantType RestaurantType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantBookingDates> RestaurantBookingDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantPhoto> RestaurantPhoto { get; set; }
    }
}
