//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhiganshinaMilana420_MarryMe.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskUsers
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateAppointment { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> Done { get; set; }
        public string AdminLastName { get; set; }
        public string AdminFirstName { get; set; }
        public byte[] AdminPhoto { get; set; }
        public Nullable<int> AdminId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
